### ISSUE TITLE
login

### ISSUE THREAD

**Issue by lorenzodatei** [GCalToolkit/GCalExtras#3]
hello, I just acquired the paid version, but there is no way to login in the add-on in chrome and use the premium features, in particular moving 80 events at a time.
Basically it does not see I am a paying user.
thank you

**Comment by GCalToolkit** [comment]
Hi, are you using the same Google account in Google Calendar that you used to register on sheets2gcal.com?

**Comment by lorenzodatei** [comment]
yes of course, ***@***.***

I have already restarted everything too....

What can I do?

thank you

**Comment by GCalToolkit** [comment]
Everything looks normal this end - we can't post email addresses here but it should be "ing dot lorenzo dot ******* at gmail dot com". If that's the one, are you logged into chrome using multiple email addresses? If so, does it work when you log out of your other accounts? You can tell if it's active if you no longer see the "Purchase" button.

**Comment by lorenzodatei** [comment]
I logged out from all other accounts, I have only the ing ..... @gmail ,
and I DOES NOT WORK.
It's still with the purchase button
[image: image.png]

**Comment by GCalToolkit** [comment]
I'm investigating right now - the only thing I can think of is maybe there's a problem for emails containing dots before the @ but nobody has ever reported this problem before so that seems unlikely. I'll refund at any point so don't worry about that, meanwhile I'm testing now with multiple Google accounts to try and reproduce the problem.

**Comment by lorenzodatei** [comment]
Hello

any news about that? I am not worried about the refund, I just would like
to have it working.

Thank you

**Comment by GCalToolkit** [comment]
Sorry for the delay - I'm still trying to reproduce the problem... hopefully I'll have some answers later today!

**Comment by GCalToolkit** [comment]
I can't reproduce this at all... Do you have access to another computer on which to test? If not, can you try opening an incognito window (or a new Chrome Profile) and logging in to Google Calendar there?

**Comment by lorenzodatei** [comment]
Hello,

still the same problem:

[image: Immagine 2024-03-27 162457.jpg]

I logged in with the email address of my subscription, and it has
always the same problem.

Are you sure it's registered under the exact email address?

thank you

LD

**Comment by GCalToolkit** [comment]
I just sent an email to the address that you used to register but it was rejected and Google tells me the account doesn't exist - can you see the problem here? BTW I can't see your screenshots... I think you have to post on Github directly for that to work.

**Comment by lorenzodatei** [comment]
Can we please check what’s the Registered email address?

Thanks

Il giorno gio 28 mar 2024 alle 15:05 GCalTools ***@***.***>
ha scritto:

**Comment by GCalToolkit** [comment]
You'll have to come directly to the GitHub page here:
https://github.com/GCalToolkit/GCalExtras/issues/3
to see the email address I posted as an image - we can't post email addresses here.

**Comment by lorenzodatei** [comment]
the address email has to be changed, it is ing.lorenzo.datei@gmail.com, can you do that please?

**Comment by GCalToolkit** [comment]
Done! Let me know if that fixes the problem - if not just sign up again with the correct email and I'll transfer your membership.

**Comment by GCalToolkit** [comment]
And you can remove your email address here now (I'll remove the image too) to avoid spam.

**Comment by lorenzodatei** [comment]
it works perfectly thank you

**Comment by GCalToolkit** [comment]
Glad we got there in the end - and thank you for your patience!
